-- Clear existing products and insert new products with care instructions
DELETE FROM products;

INSERT INTO products (name, description, price, category, weight_kg, in_stock, care_instructions) VALUES
('Cupped Hands Sculpture', 'A poetic sculptural piece depicting gently cupped hands, available in pristine white or warm terracotta finish. Perfect for holding small treasures, jewelry, or simply as a contemplative art piece.', 2800, 'Artifacts', 0.6, true, 'Clean with damp cloth followed by dry cloth'),
('Earth Tone Serving Plates', 'A stunning set of two handcrafted serving plates featuring organic brush strokes in earthy browns and creamy whites. Each plate tells a story of landscape and horizon.', 3500, 'Tableware', 1.2, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Organic Edge Platters', 'Delicate ivory-toned platters with beautifully irregular, hand-pinched edges. The subtle crystalline glaze creates a luminous, frosted appearance reminiscent of morning mist.', 3200, 'Tableware', 1.0, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Forest Green Tea Set', 'An elegant tea set featuring a plump teapot and matching cups with a distinctive two-tone design - creamy white body with deep forest green accents. Perfect for intimate tea ceremonies.', 4500, 'Tableware', 1.8, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Minimalist Cream Mugs', 'A pair of serene, cloud-like mugs in soft cream glaze. Their organic shape fits naturally in your hands, making every sip a moment of mindfulness.', 1800, 'Tableware', 0.5, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Rustic Duo Mug Set', 'A collection of artisan mugs and a creamer in contrasting two-tone finish - raw terracotta meets creamy white. Each piece celebrates the beauty of natural clay.', 2600, 'Tableware', 0.9, true, 'Food safe • Lead free • Microwave and oven friendly • Dishwasher friendly • Handwash gently with soap or detergent to extend longevity'),
('Indigo Planters', 'A trio of cylindrical planters in varying sizes with deep indigo and stormy gray glazes. Their clean lines and rich colors create a striking display for your green companions.', 2200, 'Artifacts', 1.4, true, 'Clean with damp cloth followed by dry cloth'),
('Fortune Cookie Keepsakes', 'Whimsical ceramic fortune cookies with personalized messages. Hand-painted with colorful accents, these make perfect gifts for celebrations, weddings, or simply spreading joy.', 1500, 'Artifacts', 0.3, true, 'Clean with damp cloth followed by dry cloth');